//go:build ignore

// This tool compiles GLSL shaders to SPIR-V and generates Go source with embedded bytecode.
// Usage: go run compile_shaders.go
// Requires: glslc (from Vulkan SDK) in PATH.
package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
)

type shader struct {
	glsl string
	spv  string
}

func main() {
	shaders := []shader{
		{"rect.vert.glsl", "rect.vert.spv"},
		{"rect.frag.glsl", "rect.frag.spv"},
	}

	glslc, err := exec.LookPath("glslc")
	if err != nil {
		fmt.Println("ERROR: glslc not found in PATH.")
		fmt.Println("Install the Vulkan SDK from https://vulkan.lunarg.com/sdk/home")
		fmt.Println("Then ensure glslc is in your PATH and re-run this tool.")
		os.Exit(1)
	}
	fmt.Printf("Using glslc: %s\n", glslc)

	dir, _ := filepath.Abs(".")
	for _, s := range shaders {
		src := filepath.Join(dir, s.glsl)
		dst := filepath.Join(dir, s.spv)

		cmd := exec.Command(glslc, "-O", "--target-env=vulkan1.0", src, "-o", dst)
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		fmt.Printf("Compiling %s -> %s\n", s.glsl, s.spv)
		if err := cmd.Run(); err != nil {
			fmt.Fprintf(os.Stderr, "Failed to compile %s: %v\n", s.glsl, err)
			os.Exit(1)
		}
	}

	// Generate Go source file with embedded bytecode
	generateGoEmbed(shaders)
	fmt.Println("Done! Generated ../shaders_embed.go")
}

func generateGoEmbed(shaders []shader) {
	out := `package vulkan

import _ "embed"

// Auto-generated by shaders/compile_shaders.go — DO NOT EDIT.

//go:embed shaders/rect.vert.spv
var rectVertSPV []byte

//go:embed shaders/rect.frag.spv
var rectFragSPV []byte
`
	outPath := filepath.Join("..", "shaders_embed.go")
	if err := os.WriteFile(outPath, []byte(out), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to write %s: %v\n", outPath, err)
		os.Exit(1)
	}
}
